language: python
sudo: false
# command to install dependencies
before_install: "cd tests"
install: travis_retry pip install 'tox<3.0' coveralls
# command to run tests
script:
  - npm install
  - tox -e "${TOXENV}"
after_success:
  - coverage xml
  - cp coverage.xml ../
  - coveralls
env:
  matrix:
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py27-django19
    - TOXENV=py27-django110
    - TOXENV=py27-django111
    - TOXENV=py34-django17
    - TOXENV=py34-django18
    - TOXENV=py34-django19
    - TOXENV=py34-django110
    - TOXENV=py34-django111

# Python 3.5 has to go here until Travis adds it to the default build images.
# https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django110
    - python: 3.5
      env: TOXENV=py35-django111
